# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e530315c2240aee2e2f4e9dc706a8596a1c7013418a5bd22084edbbaab708206a10d236efcc0b8d45095524d5238121d07f0619ac844856f0b2de3eea818c636

test:
  secret_key_base: 22abcd3b44338b2eec805663bd14590e3d1f33f2fc1ea5e04bdb93d10bd908a3f6f76769d61db6f285645a6ece443c286a79e5f166067f7cf391babcd51cbb84

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
